version: '3.8'
services:
  
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
#    container_name: es-container
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    ports:
#      - 9200:9200

#  kibana:
#    container_name: kb-container
#    image: docker.elastic.co/kibana/kibana:8.11.1
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    depends_on:
#      - elasticsearch
#    ports:
#      - 5601:5601
      